### ISSUE TITLE
As a engineering team member, I should try out Stacks test net & do a code review.

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-core#820]
Each team member should spend a day trying out the [Stacks test net](https://testnet.blockstack.org) and recording their experience, including what they tried and any issues they encountered in github issues.

- [ ] https://github.com/blockstack/blockstack-core/issues/821 Write testing guide (@jcnelson) 
- [ ] https://github.com/blockstack/blockstack-core/issues/823 Try test net (@kantai) 
- [ ] https://github.com/blockstack/blockstack-core/issues/824 Try test net (@hstove) 
- [ ] https://github.com/blockstack/blockstack-core/issues/825 Try test net (@yknl) 
- [ ] https://github.com/blockstack/blockstack-core/issues/822 Try test net (@larrysalibra) 
- [ ] https://github.com/blockstack/blockstack-core/issues/827 Try test net (@shea256) 
- [ ] https://github.com/blockstack/blockstack-core/issues/826 Try test net (@muneeb-ali)
